### PR TITLE
resolved faulty route and added contrinutor link

### PR DESCRIPTION
**Pull request by ME-ON1**

### CODE REVIEW

**Comment by bacloud14** [comment]
It works ! thanks Tarun

**Comment by bacloud14** [comment]
oh sorry, static resources are not loading, even xmlhttprequest requests are not loading.

**Comment by bacloud14** [comment]
**not urgent** just to say,,

**Comment by ME-ON1** [comment]
What?? Xmlhttprequest from where

**Comment by bacloud14** [comment]
yep, tapping the `nearby` API
tested this:

http://localhost:3000/nearby/%7B%22lat%22:19.5437751,%22lng%22:-96.91018059999999,%22cityname%22:%22Xalapa%22,%22language%22:%22en%22%7D

 I think we just need the `pass` there like

http://localhost:3000/blaaaa/nearby/%7B%22lat%22:19.5437751,%22lng%22:-96.91018059999999,%22cityname%22:%22Xalapa%22,%22language%22:%22en%22%7D

works when

pass=blaaaa

**Comment by bacloud14** [comment]
navbar navigation works fine. But static resources also don't work like in `http://localhost:3000/bla/ar`

**Pull request merged**
