### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by SmsS4**
Hello :)
i was working on Setup UI-test (https://github.com/bacloud14/WeatherVenue/issues/39) issue.
I used cypress for testing but due to US sanctions against Iran (where i live) i couldn't set a billing account and use google map API so i couldn't fully test my PR.

## about Cypress
[Cypress](https://www.cypress.io/) is an end-to-end testing framework for web test automation with 35.2k stars in github :)
[here](https://www.tutorialspoint.com/cypress/index.htm) is a good tutorial for cypress

## Cypress install and run
```npm install cypress --save-dev```
after install you can see some examples in cypress/integration.
for running tests on terminal you can use this command
```./node_modules/.bin/cypress run```
and for running tests on ui use 
```./node_modules/.bin/cypress open```

## Cypress CI/CD
so i wrote a workflow for cypress (.github/workflows/ci.yml)
which triggers on push to master and dev and pull request to master
```
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]
```
you can setup env like this:
```
env:
    NODE_ENV: dev
    PORT: 3000
    REDIS_PORT: 6379
    HONEYPOT_KEY: ####
    PASS: 
    OPENWEATHERMAP_API_KEY:  ${{ secrets.OPENWEATHERMAP_API_KEY }}
    GOOGLE_MAPS_API_KEY:  ${{ secrets.GOOGLE_MAPS_API_KEY }}
```
and store OPENWEATHERMAP_API_KEY and GOOGLE_MAPS_API_KEY in secrets (settings -> secrets)  
only collaborators can see secrets

i'm not sure i have to run ci on which node.js version but i saw people run on 16.x and 17.x
```
strategy:
  matrix:
    node-version: [16.x, 17.x]
```

first part of ci is just building project
```
- name: Checkout
  uses: actions/checkout@v2
- name: Use Node.js ${{ matrix.node-version }}
  uses: actions/setup-node@v2
  with:
    node-version: ${{ matrix.node-version }}
    cache: 'npm'
- run: npm ci
- run: gulp compress_js
- name: Install redis
  run: sudo apt-get install -y redis-tools redis-server
- name: Verify that redis is up
  run: redis-cli ping
```

and next two steps are running cypress tests in firefox and chrome

```
- name: Run tests in chrome
  uses: cypress-io/github-action@v2
  with:
    wait-on: 'http://localhost:3000'
    wait-on-timeout: 20
    record: false
    start: npm start
    browser: chrome
```
this step waits (with 20 seconds timeout) for http://localhost:3000  
and run ```npm start``` then run tests on chrome
and next step is for firefox

## Tests
i wrote some functions which is usefull for testing

- test_on_device: Test test_function on specified device
- test_on_all_devices: Test test_function on all devices (iphone, macbook, fullhd and 1600x900)
- test_on_mobile Test test_function on some mobile resolution (ipad-2, iphone, samsung-note, samsung-s10 and ...)
- test_on_desktop: Test test_function on some desktop resolution (macbook, fullhd, 1600*900)
you can see available devices [here](https://docs.cypress.io/api/commands/viewport#Syntax)

also weathervenue raises an exception so i had to handle it like this:
```
Cypress.on('uncaught:exception', (err, runnable) => {
    if (err.message.includes("Cannot read properties of null (reading 'dataset')")) {
        return false
    }
    return true;
});
```
cypress fails on exceptions unless handle them like above code

I'm almost sure my code works but as i said i couldn't set a billing account and fully test my PR.

(sorry for my grammar mistakes :)

### CODE REVIEW

**Comment by bacloud14** [comment]
Hello @SmsS4 
I'm impressed by how good you are in Cypress. I will be reviewing and testing this tomorrow, learning a lot along the way too !!
Thank you so much !

**Comment by bacloud14** [comment]
Everything works as expected locally, just throwing `Too Many Requests` because I set the 'express-rate-limit' middle-ware.
Could you set a delay for requests ? thanks again

**Comment by SmsS4** [comment]
thanks
how much delay should i set between requests?

**Comment by bacloud14** [comment]
I'm not very sure. 
I set this 
https://github.com/bacloud14/WeatherVenue/blob/21542ba464b4c374052345eebf684f32b30c3a2a/index.js#L34

**Comment by SmsS4** [comment]
Isn't it better that we set rate limit as environment variable? so we can speedup test time

**Comment by bacloud14** [comment]
yes this is a good idea,

**Comment by bacloud14** [comment]
It is strange, I'm deactivating the limiter on dev env, still I get the same error.

**Comment by bacloud14** [comment]
impressive. Thanks again.

**Comment by bacloud14** [comment]
Although there are some Cypress errors this is not problematic, As the
most important is that Cypress structure now is present.

However, I'm trying to merge dev into master again, I don't know what I'm
messing with earlier commits, lock file mismatch a lot. But anyway, I will
look into this again the following days.

Thank you so much as I'm also learning a few things.

Have a nice day

**Comment by SmsS4** [comment]
Hi
Looks like my nmp version is 6.14 :) so mayble that's the reason lock mismatch a lot.
you can just add cypress with your nmp to dependency and don't use my lock.

and thanks for merging pr

Have a nice day

**Comment by bacloud14** [comment]
Thanks again, nice contribution

**Pull request merged**
